[pytest]

python_files = 
    test_*.py

python_classes = 
    Test*

python_functions = 
    test_*

testpaths = 
    tests

addopts = 
    -ra
    -v
    --strict-markers
    --tb=short
    --color=yes

log_cli = true

log_cli_level = INFO

log_cli_format = 
    %(asctime)s | %(levelname)s | %(message)s

log_cli_date_format =
    %H:%M:%S

markers = 
    smoke: Smoke tests
    regression: Regression tests
    api: Api tests
    ui: Selenium UI tests
    unit: Unit tests
    integration: Integration tests
    penetration: Penetration tests
    security: Security tests
    slow: Slow tests
    db: SQLite tests
    schema: JSON Schema validation
    positive: Positive scenarios
    negative: Negative scenarios
    boundary: Boundary tests

filterwarnings = 
    ignore::DeprecationWarning